version: "3.2"
services:
  mysql_test:
    image: mariadb:10.10.2
    restart: always
    environment:
      MYSQL_DATABASE: ${NS_MARIADB_DATABASE}
      MYSQL_USER: ${NS_MARIADB_USER}
      MYSQL_PASSWORD: ${NS_MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NS_MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - db_network

volumes:
  db-data:

networks:
  db_network:
    driver: bridge
